In [12]:
import numpy as np

In [13]:
A = np.array([1,2,3,4])

In [14]:
print(A)


[1 2 3 4]


In [15]:
np.ndim(A)


1

In [16]:
A.shape


(4,)

In [17]:
A.shape[0]

4

In [18]:
B = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
np.ndim(B)

2

In [20]:
B.shape

(3, 2)

In [21]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [22]:
B = np.array([[5,6],[7,8]])
B.shape

(2, 2)

In [23]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [24]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [25]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [46]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(A.shape)
B = np.array([[7],[8]])
print(B.shape)

(3, 2)
(2, 1)


In [47]:
np.dot(A, B)  

array([[23],
       [53],
       [83]])

In [48]:
np.dot(A, B).shape

(3, 1)

In [49]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(A.shape)
B = np.array([7,8])
print(B.shape)

(3, 2)
(2,)


In [50]:
np.dot(A,B)

array([23, 53, 83])

In [51]:
np.dot(A,B).shape

(3,)

In [53]:
X = np.array(
    [1,2]
)
X.shape

(2,)

In [55]:
W = np.array([
    [1,3,5],
    [2,4,6]
])
W.shape

(2, 3)

In [56]:
Y = np.dot(X,W)
print(Y)
Y.shape

[ 5 11 17]


(3,)

## neural network sample

In [68]:
X = np.array([1.0, 0.5])
W1 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
])
B1 = np.array([0.1, 0.2, 0.3])

In [69]:
print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)
