In [1]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from src.gradient_simplenet import simpleNet
from src.loss_function import numerical_gradient

In [2]:
net = simpleNet()

In [3]:
print(net.W)

[[-0.91053819  0.24141734  0.05463673]
 [ 0.32043492 -0.51124704 -0.71756271]]


In [4]:
net2 = simpleNet()

In [5]:
print(net2.W)

[[ 0.85455218 -0.41227007  0.20589107]
 [-0.42454942  0.67874181 -0.23877973]]


In [6]:
x = np.array([0.6, 0.9])
p = net.predict(x)

In [7]:
print(p)

[-0.25793148 -0.31527194 -0.61302441]


In [8]:
np.argmax(p)

0

In [9]:
t = np.array([0, 0, 1])

In [10]:
net.loss(x, t)

1.3279075806297598

In [14]:
f = lambda w: net.loss(x, t)

In [15]:
dW = numerical_gradient(f, net.W)

In [16]:
print(dW)

[[ 0.22681036  0.21417079 -0.44098115]
 [ 0.34021554  0.32125619 -0.66147173]]
