In [2]:
import numpy as np

In [4]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [5]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [6]:
y = exp_a / sum_exp_a

In [7]:
print(y)

[0.01821127 0.24519181 0.73659691]


In [8]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))

/Users/kuesugi/Dropbox/WorkSpace/python_env/sample_deep_learning/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/Users/kuesugi/Dropbox/WorkSpace/python_env/sample_deep_learning/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [9]:
c = np.max(a)
a -c
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [10]:
import sys, os
sys.path.append(os.pardir)
from src.activation import softmax

In [11]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [12]:
np.sum(y)

1.0